// Generated by Selenium IDE
package com.sampletest;

import com.sampletest.*;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RegisterPageTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void registerPage() {
		// Test name: RegisterPage
		// Step # | name | target | value | comment
		// 1 | open | / | |
		driver.get("https://demo.nopcommerce.com/");
		// 2 | setWindowSize | 1382x744 | |
		driver.manage().window().setSize(new Dimension(1382, 744));
		// 3 | click | linkText=Register | |
		driver.findElement(By.linkText("Register")).click();
		// 4 | click | id=gender-male | |
		driver.findElement(By.id("gender-male")).click();
		// 5 | click | id=FirstName | |
		driver.findElement(By.id("FirstName")).click();
		// 6 | type | id=FirstName | Kamesh |
		driver.findElement(By.id("FirstName")).sendKeys("Kamesh");
		// 7 | click | id=LastName | |
		driver.findElement(By.id("LastName")).click();
		// 8 | type | id=LastName | P |
		driver.findElement(By.id("LastName")).sendKeys("P");
		// 9 | click | name=DateOfBirthDay | |
		driver.findElement(By.name("DateOfBirthDay")).click();
		// 10 | select | name=DateOfBirthDay | label=18 |
		{
			WebElement dropdown = driver.findElement(By.name("DateOfBirthDay"));
			dropdown.findElement(By.xpath("//option[. = '18']")).click();
		}
		// 11 | click | name=DateOfBirthMonth | |
		driver.findElement(By.name("DateOfBirthMonth")).click();
		// 12 | select | name=DateOfBirthMonth | label=May |
		{
			WebElement dropdown = driver.findElement(By.name("DateOfBirthMonth"));
			dropdown.findElement(By.xpath("//option[. = 'May']")).click();
		}
		// 13 | click | name=DateOfBirthYear | |
		driver.findElement(By.name("DateOfBirthYear")).click();
		// 14 | select | name=DateOfBirthYear | label=1924 |
		{
			WebElement dropdown = driver.findElement(By.name("DateOfBirthYear"));
			dropdown.findElement(By.xpath("//option[. = '1924']")).click();
		}
		// 15 | click | id=Email | |
		driver.findElement(By.id("Email")).click();
		// 16 | type | id=Email | abc@gmail.com |
		driver.findElement(By.id("Email")).sendKeys("abc@gmail.com");
		// 17 | click | css=.fieldset:nth-child(1) > .form-fields | |
		driver.findElement(By.cssSelector(".fieldset:nth-child(1) > .form-fields")).click();
		// 18 | click | id=Company | |
		driver.findElement(By.id("Company")).click();
		// 19 | type | id=Company | XYZ india private Ltd |
		driver.findElement(By.id("Company")).sendKeys("XYZ india private Ltd");
		// 20 | click | css=.page-body > form | |
		driver.findElement(By.cssSelector(".page-body > form")).click();
		// 21 | click | id=Password | |
		driver.findElement(By.id("Password")).click();
		// 22 | type | id=Password | Kamesh@30 |
		driver.findElement(By.id("Password")).sendKeys("Kamesh@30");
		// 23 | click | id=ConfirmPassword | |
		driver.findElement(By.id("ConfirmPassword")).click();
		// 24 | type | id=ConfirmPassword | Kamesh@30 |
		driver.findElement(By.id("ConfirmPassword")).sendKeys("Kamesh@30");
		// 25 | click | id=register-button | |
		driver.findElement(By.id("register-button")).click();
	}
}
